[package]
name = "abm-local-ai"
description = "ABM Local AI hub"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "abm_local_ai_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
abm-hub-core = { path = "../core" }
tauri = { version = "2", features = ["tray-icon"] }
serde.workspace = true
serde_json.workspace = true
